### ISSUE TITLE
Odroid-C1

### ISSUE THREAD

**Issue by katzzero** [fporter/limelight-odroid#4]
I cant use ./buildlinuxarm.sh

odroid@Odroid-C1-linux:~/Downloads/limelight-odroid/jni/nv_avc_dec$ sudo ./buildlinuxarm.sh
rm: cannot remove ‘*.o’: No such file or directory
rm: cannot remove ‘libnv_avc_dec.so’: No such file or directory
In file included from nv_avc_dec.c:21:0:
nv_avc_dec.h:1:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
In file included from nv_avc_dec_jni.c:1:0:
nv_avc_dec.h:1:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
gcc: error: *.o: No such file or directory
rm: cannot remove ‘*.o’: No such file or directory

What i´m doing wrong ?

**Comment by fporter** [comment]
There are a few possibilities.. it seems the compiler can't find jni.h which is apart of the jdk.
First, did you install openjdk-7-jdk?
In the build script it should pick up the header at "/usr/lib/jvm/java-7-openjdk-armhf/include/", if that is not the location (it moved or different platform) then you may need to update the paths in the scripts.

**Comment by katzzero** [comment]
it was exactly what you have said ... java-7-openjdk-armhf was in openjdk-7-java-armhf for some reason i dont know.
i compiled ok but it not work with geforce experience 2.4.1 ... only 2.1.1 sadly.
there any way i update it for work at least with 2.2.2 ?
Thanks for your patience ! and excelent work !! :D

**Comment by katzzero** [comment]
Another question. I have oracle jdk 8 installed too ... theres any diference if i compile with it ?

**Comment by fporter** [comment]
Maybe it was moved for newer installs, I'll see if should change that path.. probably should be dynamic.

If you pull from the main development I forked from (limelight-stream/limelight-pc) and merge, it should update what you need for the newer versions of geforce experience. It is normally painless, no guarantees. I just made it easier to compile on odroid with ubuntu (and maybe other arm devices?), I'm hoping to improve the latency/performance in a future update for arm devices... if/when i get a chance to.

I haven't tried jdk 8, i think. You can if you want.

**Comment by Kondra007** [comment]
I have another error:

```
rm: cannot remove ‘*.o’: No such file or directory
rm: cannot remove ‘libnv_avc_dec.so’: No such file or directory
nv_avc_dec.c: In function ‘update_rgb_frame’:
nv_avc_dec.c:281:3: warning: passing argument 2 of ‘sws_scale’ from incompatible pointer type
   our_yuv_frame->data,
   ^
In file included from nv_avc_dec.c:8:0:
./inc/libswscale/swscale.h:226:5: note: expected ‘const uint8_t * const*’ but argument is of type ‘uint8_t **’
 int sws_scale(struct SwsContext *c, const uint8_t *const srcSlice[],
     ^
nv_avc_dec_jni.c: In function ‘Java_com_limelight_nvstream_av_video_cpu_AvcDecoder_getRgbFrameInt’:
nv_avc_dec_jni.c:69:29: warning: passing argument 1 of ‘nv_avc_get_rgb_frame’ from incompatible pointer type
  ret = nv_avc_get_rgb_frame(jni_output_data, outlen * 4);
                             ^
In file included from nv_avc_dec_jni.c:1:0:
nv_avc_dec.h:8:5: note: expected ‘char *’ but argument is of type ‘jint *’
 int nv_avc_get_rgb_frame(char* buffer, int size);
     ^
/usr/bin/ld.bfd.real: cannot find -lavresample
collect2: error: ld returned 1 exit status
```

**Comment by katzzero** [comment]
You need libavcodec for this ..
 Em 12/04/2015 15:21, "Kondra007" <notifications@github.com> escreveu:
